project:
  type: book
  output-dir: docs
  
book:
  title: "LabFisFQ"
  author: "JEBV"
  date: "03/28/2023"
  chapters:
    - index.qmd
    - tarea1.qmd
    - tarea2.qmd
    - tarea2_bis.qmd
    - tarea3.qmd
    - caidalibre.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: minty
    fontsize: 0.6em

